classDiagram
    class cpu_topo {
        +cpu_set process_affinity
        +Vector~cpu_id~ cpu_ids
        +Vector~ApicIdCountMap~ lvl_ids
        +count() size_t
        +max_domain() cpu_domain
        +count_domain(cpu_domain lvl) size_t
        +parse_topology() void
        +refresh() void
    }

    class cpu_id {
        +cpuid(leaf, subleaf) cpuid_result
        +max_leaf() unsigned
        +id_leaf() unsigned
        +masked_id(domain) apic_id
        +operator()(feature) bool
        +brand_string() string
        +efficiency() cpu_efficiency
        #retrieve(leaf) CpuidResultList
    }

    class cpu_set {
        -int sz
        -cpu_set_t set
        -GROUP_AFFINITY ga
        -DWORD_PTR sysAffinity
        +get_logical_cpu_count() unsigned
        +applyToCurrentThread() bool
        +query() bool
        +apply() bool
        +operator|(cpu_set) cpu_set
        +operator&(cpu_set) cpu_set
        +operator+=(cpu_id) cpu_set
    }

    class cpuid_result {
        <<union>>
        +unsigned r
        +unsigned ax
        +unsigned bx
        +unsigned cx
        +unsigned dx
    }

    class apicid_bit_layout {
        +cpu_domain domain
        +unsigned shift
        +mask_map relative_masks
    }

    class apicid_bit_layouts {
        +cpu_domain top_domain
        +domains() unsigned
    }

    class mask_map {
        +operator[](key) id_mask
    }

    class Map {
        <<external STL base>>
    }

    class Vector {
        <<external STL base>>
    }

    class cpu_feature {
        <<enumeration>>
        SSE3
        AVX
        AVX2
        AVX512F
        AMX_TILE
    }

    class cpu_domain {
        <<enumeration>>
        InvalidDomain
        LogicalDomain
        CoreDomain
        ModuleDomain
        TileDomain
        DieDomain
        DieGrpDomain
    }

    class cpu_processor_type {
        <<enumeration>>
        OEM_processor
        IntelOverDrive
        Dual_processor
        Intel_reserved
    }

    class cpu_core_type {
        <<enumeration>>
        DUNNO
        RESRV
        AtomR
        R3SRV
        CoreI
    }

    class cpu_efficiency {
        <<enumeration>>
        unknownEff
        effficient
        performant
    }

    class init_type {
        <<enumeration>>
        process
        empty
    }

    class ApicIdCountMap {
        <<container type>>
    }

    class CpuidResultList {
        <<container type>>
    }

    Map <|-- cpu_id
    Map <|-- mask_map
    Vector <|-- apicid_bit_layouts
    cpu_topo "1" *-- "1" cpu_set : process affinity
    cpu_topo "1" *-- "0..*" cpu_id : CPU records
    cpu_topo --> ApicIdCountMap : lvl_ids
    apicid_bit_layout *-- mask_map : relative masks
    cpu_id --> CpuidResultList : leaf results
    cpu_id --> cpuid_result : CPUID data
    cpu_topo --> cpu_domain
    cpu_id --> cpu_feature
    cpu_id --> cpu_efficiency
    cpu_id --> cpu_processor_type
    cpu_id --> cpu_core_type
    cpu_set --> init_type